# Generated by Django 4.0.6 on 2022-07-14 00:18

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertion_date', models.DateTimeField(auto_now_add=True, verbose_name='Insertion Date')),
                ('modification_date', models.DateTimeField(auto_now_add=True, verbose_name='Modification Date')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=apps.products.models.product_directory_path, verbose_name='Product Image')),
                ('product_slug', models.SlugField(unique=True, verbose_name='Product Slug')),
                ('url', models.URLField(verbose_name='Product Url')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateTimeField(auto_now_add=True, verbose_name='Modification Date')),
                ('is_active', models.BooleanField(default=True)),
                ('insertion_date', models.DateField(auto_now_add=True, verbose_name='Insertion Date')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.productsmodel', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
