# Generated by Django 4.0.6 on 2022-07-13 04:49

from django.db import migrations, models

import services.cpf


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_usermodel_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="document",
            field=models.CharField(
                help_text="Just numbers",
                max_length=11,
                validators=[services.cpf.CPFLogics.validate_cpf],
                verbose_name="User Document",
            ),
        ),
    ]
